# Stage 1: Build
FROM node:18-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps

COPY . .

# VITE_ vars are baked in at build time
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_PUBLISHABLE_KEY
ARG VITE_SUPABASE_PROJECT_ID
ARG VITE_MASTER_PASSWORD
ARG VITE_LOGIN_USERNAME
ARG VITE_LOGIN_PASSWORD
ARG VITE_DEFAULT_EMAIL
ARG VITE_DEFAULT_PASSWORD

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_PUBLISHABLE_KEY=$VITE_SUPABASE_PUBLISHABLE_KEY
ENV VITE_SUPABASE_PROJECT_ID=$VITE_SUPABASE_PROJECT_ID
ENV VITE_MASTER_PASSWORD=$VITE_MASTER_PASSWORD
ENV VITE_LOGIN_USERNAME=$VITE_LOGIN_USERNAME
ENV VITE_LOGIN_PASSWORD=$VITE_LOGIN_PASSWORD
ENV VITE_DEFAULT_EMAIL=$VITE_DEFAULT_EMAIL
ENV VITE_DEFAULT_PASSWORD=$VITE_DEFAULT_PASSWORD

RUN npm run build

# Stage 2: Serve
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
