
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
// Removed Database generic import to avoid type mismatch issues with new tables
// import type { Database } from './types';

const SUPABASE_URL = "https://umrrchfsbazjqopaxkoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtcnJjaGZzYmF6anFvcGF4a29pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MDIwMTksImV4cCI6MjA2Njk3ODAxOX0.mrzTjjqFGecqbIs-iCkAnokjAQiX_NP7UYKi3PiAkgo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
